v4.5.7 - SourceCode only

diff --git a/ZimbraServer/src/bin/zmtrainsa b/ZimbraServer/src/bin/zmtrainsa
--- a/ZimbraServer/src/bin/zmtrainsa
+++ b/ZimbraServer/src/bin/zmtrainsa
@@ -101,6 +101,11 @@ if [ x`whoami` != xzimbra ]; then
 	exit 1
 fi
 
+if [ ! -h "/opt/zimbra/amavisd" ]; then
+    echo "Error: SpamAssassin not installed"
+    exit 1
+fi
+
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
 	zimbra_home \
@@ -129,7 +134,7 @@ if [ "x${MODE}" != "xspam" -a "x${MODE}" != "xham" ]; then
   usage
 fi
 
-if [ "x${FOLDER}" = "x" -o "x${USER}" = "x" ]; then
+if [ "x${USER}" = "x" ]; then
   usage
 fi
 
